name: Build and Push iTop Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'itop-list.json'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Read iTop Versions and Build Images
      run: |
        mkdir -p dockerfiles
        jq -c '.iTops[]' itop-list.json | while read i; do
          ITOP_NAME=$(echo $i | jq -r '.name')
          DOWNLOAD_URL=$(echo $i | jq -r '.downloadUrl')
          PHP_VERSION=$(echo $i | jq -r '.phpVersion')
          VERSION_TAG=$(echo $ITOP_NAME | sed 's/iTop-//') # Remove prefix 'iTop-'
          DIR_NAME="dockerfiles/$VERSION_TAG"
          mkdir -p $DIR_NAME
          cp Dockerfile $DIR_NAME/Dockerfile
          sed -i "s|ARG ITOP_URL=.*|ARG ITOP_URL=$DOWNLOAD_URL|" $DIR_NAME/Dockerfile
          sed -i "s|ARG PHP_VERSION=.*|ARG PHP_VERSION=$PHP_VERSION|" $DIR_NAME/Dockerfile

          # Calcul du hash du Dockerfile
          DOCKERFILE_HASH=$(sha256sum $DIR_NAME/Dockerfile | cut -d ' ' -f 1)
          IMAGE_NAME="alxfrst/itop:$VERSION_TAG-$DOCKERFILE_HASH"

          # Vérification si l'image existe déjà avec ce hash
          if docker pull $IMAGE_NAME; then
            echo "Image already exists with the same configuration, skipping build and push."
          else
            docker buildx build --push --tag $IMAGE_NAME --build-arg ITOP_URL=$DOWNLOAD_URL --build-arg PHP_VERSION=$PHP_VERSION $DIR_NAME
          fi
        done
      shell: bash

    - name: Clean up
      run: rm -rf dockerfiles
